.PHONY: 1.0.0 1.0.1 1.1.0 1.2.0 3.0.8 3.0.13 3.0.14 3.0.15 3.0.15.1 3.0.16

all: 1.0.0 1.0.1 1.1.0 1.2.0 3.0.8 3.0.13 3.0.14 3.0.15 3.0.15.1 3.0.16

1.0.0:
	ds importpdb assets/openssl.flirt 1.0.0/x86/openssl.exe 1.0.0/x86/openssl.pdb openssl 1.0.0
	ds importpdb assets/openssl.flirt 1.0.0/x86/libcrypto-1_1.dll 1.0.0/x86/libcrypto-1_1.pdb openssl 1.0.0
	ds importpdb assets/openssl.flirt 1.0.0/x86/libssl-1_1.dll 1.0.0/x86/libssl-1_1.pdb openssl 1.0.0

1.0.1:
	ds importpdb assets/openssl.flirt 1.0.1/x86/openssl.exe 1.0.1/x86/openssl.pdb openssl 1.0.1
	ds importpdb assets/openssl.flirt 1.0.1/x86/libcrypto-1_1.dll 1.0.1/x86/libcrypto-1_1.pdb openssl 1.0.1
	ds importpdb assets/openssl.flirt 1.0.1/x86/libssl-1_1.dll 1.0.1/x86/libssl-1_1.pdb openssl 1.0.1

1.1.0:
	ds importpdb assets/openssl.flirt 1.1.0/x86/openssl.exe 1.1.0/x86/openssl.pdb openssl 1.1.0
	ds importpdb assets/openssl.flirt 1.1.0/x86/libcrypto-1_1.dll 1.1.0/x86/libcrypto-1_1.pdb openssl 1.1.0
	ds importpdb assets/openssl.flirt 1.1.0/x86/libssl-1_1.dll 1.1.0/x86/libssl-1_1.pdb openssl 1.1.0

1.2.0:
	ds importpdb assets/openssl.flirt 1.2.0/x86/openssl.exe 1.2.0/x86/openssl.pdb openssl 1.2.0
	ds importpdb assets/openssl.flirt 1.2.0/x86/libcrypto-1_1.dll 1.2.0/x86/libcrypto-1_1.pdb openssl 1.2.0
	ds importpdb assets/openssl.flirt 1.2.0/x86/libssl-1_1.dll 1.2.0/x86/libssl-1_1.pdb openssl 1.2.0

3.0.8:
	ds importpdb assets/openssl.flirt 3.0.8/x86/openssl.exe 3.0.8/x86/openssl.pdb openssl 3.0.8
	ds importpdb assets/openssl.flirt 3.0.8/x86/libcrypto-3.dll 3.0.8/x86/libcrypto-3.pdb openssl 3.0.8
	ds importpdb assets/openssl.flirt 3.0.8/x86/libssl-3.dll 3.0.8/x86/libssl-3.pdb openssl 3.0.8

3.0.13:
	ds importpdb assets/openssl.flirt 3.0.13/x86/openssl.exe 3.0.13/x86/openssl.pdb openssl 3.0.13
	ds importpdb assets/openssl.flirt 3.0.13/x86/libcrypto-3.dll 3.0.13/x86/libcrypto-3.pdb openssl 3.0.13
	ds importpdb assets/openssl.flirt 3.0.13/x86/libssl-3.dll 3.0.13/x86/libssl-3.pdb openssl 3.0.13

3.0.14:
	ds importpdb assets/openssl.flirt 3.0.14/x86/openssl.exe 3.0.14/x86/openssl.pdb openssl 3.0.14
	ds importpdb assets/openssl.flirt 3.0.14/x86/libcrypto-3.dll 3.0.14/x86/libcrypto-3.pdb openssl 3.0.14
	ds importpdb assets/openssl.flirt 3.0.14/x86/libssl-3.dll 3.0.14/x86/libssl-3.pdb openssl 3.0.14

3.0.15:
	ds importpdb assets/openssl.flirt 3.0.15/x86/openssl.exe 3.0.15/x86/openssl.pdb openssl 3.0.15
	ds importpdb assets/openssl.flirt 3.0.15/x86/libcrypto-3.dll 3.0.15/x86/libcrypto-3.pdb openssl 3.0.15
	ds importpdb assets/openssl.flirt 3.0.15/x86/libssl-3.dll 3.0.15/x86/libssl-3.pdb openssl 3.0.15

3.0.15.1:
	ds importpdb assets/openssl.flirt 3.0.15.1/x86/openssl.exe 3.0.15.1/x86/openssl.pdb openssl 3.0.15.1
	ds importpdb assets/openssl.flirt 3.0.15.1/x86/libcrypto-3.dll 3.0.15.1/x86/libcrypto-3.pdb openssl 3.0.15.1
	ds importpdb assets/openssl.flirt 3.0.15.1/x86/libssl-3.dll 3.0.15.1/x86/libssl-3.pdb openssl 3.0.15.1

3.0.16:
	ds importpdb assets/openssl.flirt 3.0.16/x86/openssl.exe 3.0.16/x86/openssl.pdb openssl 3.0.16
	ds importpdb assets/openssl.flirt 3.0.16/x86/libcrypto-3.dll 3.0.16/x86/libcrypto-3.pdb openssl 3.0.16
	ds importpdb assets/openssl.flirt 3.0.16/x86/libssl-3.dll 3.0.16/x86/libssl-3.pdb openssl 3.0.16

clean:
	rm -f assets/*.flirt*
